Fixed issue 5
medhatelmasry/PHP_Students_CRUD pull request #14
Opened 2021-02-13 03:19 UTC by NJoban

Added output buffer, since there are multiple include headers across the app.

2021-02-13 03:30 UTC, medhatelmasry requested changes
Unfortunately, this does not solve the database buffer overflow problem.

2021-02-13 03:35 UTC, NJoban commented
Wait, but I thought I was only supposed to fix issue 5 which was the docker-compose delete BUG, which it does fix.
-------- Original message --------From: Medhat Elmasry <notifications@github.com> Date: 2021-02-12  7:30 p.m.  (GMT-08:00) To: medhatelmasry/PHP_Students_CRUD <PHP_Students_CRUD@noreply.github.com> Cc: Joban <joban.nijjer145@gmail.com>, Author <author@noreply.github.com> Subject: Re: [medhatelmasry/PHP_Students_CRUD] Fixed issue 5 (#14) 
@medhatelmasry requested changes on this pull request.

Unfortunately, this does not solve the database buffer overflow problem.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

2021-02-13 03:56 UTC, medhatelmasry reviewed
OK. I get it. This change must be thoroughly tested because it could affect all other PHP pages.

2021-02-13 04:04 UTC, NJoban commented
Ok, uh this new fix should be better since it only changes the process_delete.php file, I'm not sure how to do the pull request again, or if it's already here.

2021-02-14 20:01 UTC, medhatelmasry approved these changes
Tested and works OK

2021-02-14 20:02 UTC, merged